# /// script
# requires-python = ">=3.12,<3.14"
# dependencies = ["tokenizers==0.23.2", "numpy==2.5.3", "pyarrow==25.0.1"]
# ///
"""Positive-control English TinyStories SUBSET, not newly generated workshop data.

Official first of four training Parquet shards and official validation, pinned by
repository revision and LFS SHA256. New training-only byte-level BPE. No pickle.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import heapq
import json
from pathlib import Path
import time
import urllib.request

ROOT = Path(__file__).resolve().parent
REVISION = 'f54c09fd23315a6f9c86f9dc80f725de7d8f9c64'
REPOSITORY = 'roneneldan/TinyStories'
FILES = [
    dict(name='train-00000-of-00004-2d5a1467fff1081b.parquet',size=248731111,checksum='77cf780cebe52b6e83e3a2ac84bc56d8059363113e41d17a023f1d8b2ed0fc0b'),
    dict(name='validation-00000-of-00001-869c898b519ad725.parquet',size=9989127,checksum='33406a6206554cfc279c29c11f4df51528af487aa1a602b075566fc83c49dcab'),
]
for item in FILES:
    item.update(hash_algorithm='sha256',url=f'https://huggingface.co/datasets/{REPOSITORY}/resolve/{REVISION}/data/'+item['name'])


def save(path, value):
    Path(path).write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')


def download(out):
    from download_scratch_corpus import download as fetch
    folder=out/'source';folder.mkdir(parents=True,exist_ok=True)
    # Metadata is preserved independently of our handwritten pin constants.
    url=f'https://huggingface.co/api/datasets/{REPOSITORY}/tree/{REVISION}?recursive=true&expand=false'
    with urllib.request.urlopen(url,timeout=30) as response:
        metadata=json.load(response)
    for item in FILES:
        actual=next(r for r in metadata if r.get('path')=='data/'+item['name'])
        if actual['size']!=item['size'] or actual['lfs']['oid']!=item['checksum']:
            raise ValueError('Official pinned metadata differs from file manifest')
    save(folder/'official_tree.json',metadata)
    readme_url=f'https://huggingface.co/datasets/{REPOSITORY}/raw/{REVISION}/README.md'
    with urllib.request.urlopen(readme_url,timeout=30) as response:
        (folder/'README.md').write_bytes(response.read())
    save(folder/'sources.json',dict(repository=REPOSITORY,revision=REVISION,files=FILES,
        license='CDLA-Sharing-1.0',license_url='https://cdla.dev/sharing-1-0/',
        license_declaration=readme_url,provenance='Existing synthetic GPT-3.5/GPT-4 stories published by TinyStories authors; not generated by this workshop.'))
    with ThreadPoolExecutor(max_workers=2) as pool:
        list(pool.map(lambda item:fetch(item,folder),FILES))


def stories(path):
    import pyarrow.parquet as pq
    for batch in pq.ParquetFile(path).iter_batches(batch_size=256,columns=['text']):
        for text in batch.column(0).to_pylist():
            if not isinstance(text,str):
                raise ValueError('Expected a text-only story column')
            yield text


def story_hash(text):
    # Group whitespace-only boundary differences without changing stored text.
    return hashlib.sha256(text.strip().encode('utf-8')).hexdigest()


def prepare(out):
    import numpy as np
    from tokenizers import Tokenizer,models,trainers,pre_tokenizers,decoders
    from download_scratch_corpus import verify
    if (out/'tokens.json').exists():
        raise FileExistsError('Dataset already prepared')
    started=time.monotonic();folder=out/'source'
    for item in FILES:verify(folder/item['name'],item)
    train_path=folder/FILES[0]['name'];valid_path=folder/FILES[1]['name']
    train_hashes=set();sample=[];train_empty=0;train_rows=0
    for index,text in enumerate(stories(train_path)):
        train_rows+=1
        if not text.strip():train_empty+=1;continue
        train_hashes.add(story_hash(text))
        rank=int(hashlib.sha256(str(index).encode()).hexdigest(),16)
        entry=(-rank,index,text)
        if len(sample)<2048:heapq.heappush(sample,entry)
        elif rank < -sample[0][0]:heapq.heapreplace(sample,entry)
    print('Audited training shard',train_rows,'stories;',len(train_hashes),'unique story hashes',flush=True)
    tok=Tokenizer(models.BPE())
    tok.pre_tokenizer=pre_tokenizers.ByteLevel(add_prefix_space=False)
    tok.decoder=decoders.ByteLevel()
    trainer=trainers.BpeTrainer(vocab_size=8192,min_frequency=1,initial_alphabet=pre_tokenizers.ByteLevel.alphabet(),special_tokens=['<|endoftext|>'])
    sample=sorted(sample,reverse=True)
    tok.train_from_iterator((text for _,_,text in sample),trainer=trainer)
    tok.save(str(out/'tokenizer.json'));eod=tok.token_to_id('<|endoftext|>')
    with (out/'tokenizer_sample.jsonl').open('w',encoding='utf-8') as f:
        for _,index,text in sample:f.write(json.dumps(dict(source_row=index,text=text),ensure_ascii=False)+'\n')
    counts={s:dict(tokens=0,articles=0,utf8_bytes=0) for s in ('train','dev','test')}
    hashes={s:hashlib.sha256() for s in counts}
    row_files={s:(out/f'{s}.jsonl').open('w',encoding='utf-8') for s in counts}
    bin_files={s:(out/f'{s}.bin').open('wb') for s in counts}
    validation_seen=set();excluded=dict(train_empty=train_empty,validation_empty=0,validation_duplicate=0,validation_overlaps_training=0)
    sample_rows=[]
    def flush(batch):
        encoded=tok.encode_batch([r['text'] for r in batch],add_special_tokens=False)
        for row,encoding in zip(batch,encoded):
            if tok.decode(encoding.ids,skip_special_tokens=False)!=row['text']:
                raise ValueError('Story does not round-trip')
            split=row['split'];blob=np.asarray(encoding.ids+[eod],dtype='<u2').tobytes()
            bin_files[split].write(blob);hashes[split].update(blob)
            row_files[split].write(json.dumps(row,ensure_ascii=False)+'\n')
            counts[split]['tokens']+=len(encoding.ids)+1
            counts[split]['articles']+=1
            counts[split]['utf8_bytes']+=len(row['text'].encode('utf-8'))
        batch.clear()
    try:
        for source_name,path in [('validation',valid_path),('train',train_path)]:
            batch=[]
            for index,text in enumerate(stories(path)):
                if not text.strip():
                    if source_name=='validation':excluded['validation_empty']+=1
                    continue
                group=story_hash(text)
                if source_name=='validation':
                    if group in train_hashes:excluded['validation_overlaps_training']+=1;continue
                    if group in validation_seen:excluded['validation_duplicate']+=1;continue
                    validation_seen.add(group)
                    split='dev' if int(group[:16],16)%2==0 else 'test'
                else:split='train'
                row=dict(source=source_name,source_row=index,split=split,text=text,
                         text_sha256=hashlib.sha256(text.encode('utf-8')).hexdigest(),group_sha256=group)
                batch.append(row)
                if source_name=='train' and len(sample_rows)<10:sample_rows.append(row)
                if len(batch)==256:flush(batch)
                if index and index%50000==0:print(source_name,index,'elapsed',round(time.monotonic()-started,1),flush=True)
            if batch:flush(batch)
    finally:
        for f in [*row_files.values(),*bin_files.values()]:f.close()
    for split,stats in counts.items():
        stats.update(sha256=hashes[split].hexdigest(),tokens_per_utf8_byte=stats['tokens']/stats['utf8_bytes'])
    extraction=dict(repository=REPOSITORY,revision=REVISION,files=FILES,
        selection='Only the first of four official training Parquet shards; all official validation stories except exact normalized-text overlaps/duplicates.',
        provenance='Existing synthetic GPT-3.5/GPT-4 stories published by TinyStories authors; not newly generated by this workshop.',
        license='CDLA-Sharing-1.0',license_url='https://cdla.dev/sharing-1-0/',
        license_declaration=f'https://huggingface.co/datasets/{REPOSITORY}/raw/{REVISION}/README.md',
        tokenizer_sample='2048 training rows with smallest SHA256(source row index) rank; no validation used.',
        tokenizer_training='ByteLevel BPE vocab8192, minimum pair frequency1, full byte alphabet, one EOD special token.',
        split='Training remains the selected official train shard. Official validation minus training-overlap hashes is deduplicated and split dev/test by SHA256(stripped original text) first16 hex parity.',
        normalization='None in stored story text; surrounding whitespace ignored only for duplicate grouping.',
        excluded=excluded,train_rows=train_rows,unique_train_story_hashes=len(train_hashes),
        counts=counts,roundtrip_verified_every_story=True,
        limitations=['SUBSET, not the full TinyStories dataset.','English synthetic simple stories; not evidence of Polish factual knowledge.','Exact deduplication only, no semantic near-duplicate audit.'])
    manifest=dict(vocab_size=tok.get_vocab_size(),eod_id=eod,dtype='little-endian uint16',
        source_label='English TinyStories synthetic SUBSET: official first of four training Parquet shards; existing GPT-3.5/GPT-4 stories, not newly generated',
        tokenizer_origin='New English8192 ByteLevel BPE trained on2048 selected training-only TinyStories subset stories',
        tokenizer_sha256=hashlib.sha256((out/'tokenizer.json').read_bytes()).hexdigest(),
        generation_prompts=['Once upon a time,','Lily found a','One day, a little boy','The dog was'],
        quality_prompts=['Once upon a time,','Lily found a','One day, a little boy','The dog was','Tom wanted to','There was a small','The little girl saw','When the rain stopped,'],
        quality_fact_probes=[],splits=counts,extraction=extraction,
        packing='Original story plus one EOD; causal windows may cross story boundaries.',seconds=time.monotonic()-started)
    save(out/'tokens.json',manifest);save(out/'extraction.json',extraction);save(out/'audit_sample.json',sample_rows)
    print(json.dumps(dict(seconds=manifest['seconds'],counts=counts,excluded=excluded)),flush=True)


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output',type=Path,default=ROOT/'data/tinystories-v1')
    p.add_argument('--stage',choices=['download','prepare','all'],default='all')
    a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
    if a.stage in ('download','all'):download(a.output)
    if a.stage in ('prepare','all'):prepare(a.output)
